CREATE DATABASE IF NOT EXISTS BD_ES3 DEFAULT CHARACTER SET utf8mb4; 
#COLLATE utf8mb4_general_ci;

USE BD_ES3;

CREATE TABLE IF NOT EXISTS LOCAIS_CONTROLADOS(
	local_id INT AUTO_INCREMENT PRIMARY KEY,
	local_nome VARCHAR(30) NOT NULL,
    local_descricao VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS PESSOAS(
	pessoa_id INT AUTO_INCREMENT PRIMARY KEY,
	pessoa_nome VARCHAR(60) NOT NULL,
	pessoa_cpf CHAR(11) UNIQUE NOT NULL,
	pessoa_data_nasc DATE NOT NULL,
	pessoa_telef VARCHAR(11),
	pessoa_email VARCHAR(100),
	pessoa_ativa TINYINT NOT NULL,
	pessoa_tipo CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS CASAS(
	casa_id INT AUTO_INCREMENT PRIMARY KEY,
	casa_ender VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MORADORES(
	morador_id INT PRIMARY KEY,
	FOREIGN KEY (morador_id) REFERENCES PESSOAS(pessoa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS PRESTADORES(
	prestador_id INT PRIMARY KEY,
	prestador_cnpj CHAR(14),
	prestador_empresa VARCHAR(150),
	FOREIGN KEY (prestador_id) REFERENCES PESSOAS(pessoa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS VISITANTES(
	visitante_id INT PRIMARY KEY,
	morador_id INT NULL,
	visit_data_autorizacao DATETIME,
	FOREIGN KEY (visitante_id) REFERENCES PESSOAS(pessoa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY (morador_id) REFERENCES MORADORES(morador_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS VEICULOS(
	vei_placa VARCHAR(8) PRIMARY KEY,
	pessoa_id INT NULL,
	vei_cor VARCHAR(20),
	vei_modelo VARCHAR(40),
	FOREIGN KEY (pessoa_id) REFERENCES PESSOAS(pessoa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS MORADOR_CASA(
	mor_cas_id INT AUTO_INCREMENT PRIMARY KEY,
	morador_id INT NULL,
	casa_id INT NULL,
	tipo_vinculo ENUM('proprietario', 'inquilino', 'dependente') NOT NULL,
	FOREIGN KEY (morador_id) REFERENCES MORADORES(morador_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY (casa_id) REFERENCES CASAS(casa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS AUTORIZACOES(
	aut_id INT AUTO_INCREMENT PRIMARY KEY,
	pessoa_id INT NULL,
	local_id INT NULL,
	FOREIGN KEY (pessoa_id) REFERENCES PESSOAS(pessoa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY (local_id) REFERENCES LOCAIS_CONTROLADOS(local_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS SERVICOS(
	serv_id INT AUTO_INCREMENT PRIMARY KEY,
	morador_id INT NULL,
	prestador_id INT NULL,
	serv_tipo VARCHAR(20),
	data_inicio DATE NOT NULL,
	data_fim DATE,
	FOREIGN KEY (morador_id) REFERENCES MORADORES(morador_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY (prestador_id) REFERENCES PRESTADORES(prestador_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS ACESSOS(
	acesso_id INT AUTO_INCREMENT PRIMARY KEY,
	local_id INT NULL,
	pessoa_id INT NULL,
	acesso_data DATETIME NOT NULL,
	acesso_tipo ENUM('entrada', 'saida') NOT NULL,
	acesso_status ENUM('permitido', 'negado') NOT NULL,
	FOREIGN KEY (local_id) REFERENCES LOCAIS_CONTROLADOS(local_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY (pessoa_id) REFERENCES PESSOAS(pessoa_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);
